apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: fluxer
data:
  livekit.yaml: |
    port: 7880

    keys:
      'APIKEY': 'APISECRET'

    rtc:
      tcp_port: 7881

    turn:
      enabled: true
      udp_port: 3478

    room:
      auto_create: true
      max_participants: 100
      empty_timeout: 300
